"use client";
import {useEffect,useMemo,useState} from "react";

type Q={section:"Listening"|"Reading & Writing";type:"choice"|"input"|"tf";prompt:string;opts?:string[];answer?:string;visual:string;audio?:string};

const questions:Q[]=[
{section:"Listening",type:"choice",prompt:"What colour is the apple?",opts:["Red","Blue","Green"],answer:"Red",visual:"ball",audio:"What colour is the apple? The apple is red."},
{section:"Listening",type:"choice",prompt:"How many apples are there?",opts:["Two","Three","Four"],answer:"Three",visual:"apples",audio:"How many apples are there? There are three apples."},
{section:"Listening",type:"choice",prompt:"What is this?",opts:["A book","A pencil","A bag"],answer:"A book",visual:"book",audio:"Look at the picture. What is this? It is a book."},
{section:"Listening",type:"choice",prompt:"Where is the cat?",opts:["Under the table","On the bed","In the bag"],answer:"Under the table",visual:"cat",audio:"Where is the cat? The cat is under the table."},
{section:"Listening",type:"choice",prompt:"How old is Ben?",opts:["Six","Seven","Eight"],answer:"Seven",visual:"child",audio:"How old is Ben? Ben is seven."},
{section:"Listening",type:"choice",prompt:"Which animal says 'meow'?",opts:["A dog","A cat","A bird"],answer:"A cat",visual:"cat",audio:"Which animal says meow? A cat says meow."},
{section:"Listening",type:"choice",prompt:"What colour is the bag?",opts:["Blue","Yellow","Pink"],answer:"Blue",visual:"bag",audio:"What colour is the bag? The bag is blue."},
{section:"Listening",type:"choice",prompt:"What colour is Tom's ball?",opts:["Yellow","Red","Green"],answer:"Yellow",visual:"garden",audio:"Tom is in the garden. His ball is yellow. What colour is Tom's ball?"},
{section:"Listening",type:"choice",prompt:"Which girl is wearing the hat?",opts:["Girl A","Girl B","Girl C"],answer:"Girl A",visual:"girls",audio:"Look carefully. Which girl is wearing the hat?"},
{section:"Listening",type:"choice",prompt:"What is on the table?",opts:["A cup","A book","A ball"],answer:"A cup",visual:"table",audio:"Look at the table. What is on the table? A cup."},
{section:"Listening",type:"choice",prompt:"Where is the teddy?",opts:["In the box","On the chair","Under the bed"],answer:"On the chair",visual:"teddy",audio:"Where is the teddy? The teddy is on the chair."},
{section:"Listening",type:"choice",prompt:"What number do you hear?",opts:["14","40","4"],answer:"14",visual:"number",audio:"Fourteen."},
{section:"Listening",type:"choice",prompt:"What colour is the star?",opts:["Purple","Orange","Green"],answer:"Orange",visual:"star",audio:"What colour is the star? The star is orange."},
{section:"Listening",type:"choice",prompt:"Who is wearing red?",opts:["Mia","Leo","Sam"],answer:"Leo",visual:"family",audio:"Mia is wearing blue. Leo is wearing red. Sam is wearing green. Who is wearing red?"},
{section:"Listening",type:"choice",prompt:"What does Anna want?",opts:["A bike","A kite","A doll"],answer:"A kite",visual:"park",audio:"Anna is in the park. She wants a kite. What does Anna want?"},
{section:"Listening",type:"choice",prompt:"Which picture shows the boy sleeping?",opts:["Picture A","Picture B","Picture C"],answer:"Picture B",visual:"differences",audio:"Look at the three pictures. Which picture shows the boy sleeping?"},
{section:"Listening",type:"choice",prompt:"Where is the pencil?",opts:["Next to the book","Behind the bag","In the box"],answer:"Next to the book",visual:"desk",audio:"Where is the pencil? It is next to the book."},
{section:"Listening",type:"choice",prompt:"How many balloons?",opts:["Five","Six","Seven"],answer:"Six",visual:"balloons",audio:"Look at the balloons. How many are there? Six."},
{section:"Listening",type:"choice",prompt:"Where is the boy?",opts:["At home","At the park","At school"],answer:"At the park",visual:"kite",audio:"The boy is at the park. Where is the boy?"},
{section:"Listening",type:"choice",prompt:"What is the last colour you hear?",opts:["Yellow","Blue","Red"],answer:"Red",visual:"colours",audio:"Yellow, blue and red. What is the last colour you hear?"},

{section:"Reading & Writing",type:"tf",prompt:"The dog is big. Is this true?",opts:["Yes","No"],answer:"Yes",visual:"dog"},
{section:"Reading & Writing",type:"tf",prompt:"Look at the picture. Is the cat under the chair?",opts:["Yes","No"],answer:"Yes",visual:"cat"},
{section:"Reading & Writing",type:"choice",prompt:"Emma has two pencils. How many pencils does Emma have?",opts:["One","Two","Three"],answer:"Two",visual:"pencils"},
{section:"Reading & Writing",type:"choice",prompt:"The sun is yellow. What colour is the sun?",opts:["Blue","Yellow","Black"],answer:"Yellow",visual:"sun"},
{section:"Reading & Writing",type:"choice",prompt:"Ben likes apples. What does Ben like?",opts:["Apples","Cars","Dogs"],answer:"Apples",visual:"apples"},
{section:"Reading & Writing",type:"choice",prompt:"Tom is with his mother. Who is with Tom?",opts:["His mother","His teacher","His friend"],answer:"His mother",visual:"family"},
{section:"Reading & Writing",type:"choice",prompt:"Tom wants a football. What does he want?",opts:["A football","A bike","A book"],answer:"A football",visual:"ball"},
{section:"Reading & Writing",type:"choice",prompt:"Lucy has a brown dog. What colour is the dog?",opts:["Brown","White","Black"],answer:"Brown",visual:"dog"},
{section:"Reading & Writing",type:"input",prompt:"Write the word for the picture.",answer:"cat",visual:"cat"},
{section:"Reading & Writing",type:"input",prompt:"Write the word for the picture.",answer:"apple",visual:"apples"},
{section:"Reading & Writing",type:"input",prompt:"Put the letters in the right order: G • O • D",answer:"dog",visual:"dog"},
{section:"Reading & Writing",type:"input",prompt:"Complete: My name is ______.",answer:"personal",visual:"child"},
{section:"Reading & Writing",type:"input",prompt:"Complete: I am ______ years old.",answer:"personal",visual:"child"},
{section:"Reading & Writing",type:"choice",prompt:"What colour is the dog?",opts:["Brown","Blue","Green"],answer:"Brown",visual:"dog"},
{section:"Reading & Writing",type:"choice",prompt:"Choose the missing word: I ___ seven.",opts:["am","is","are"],answer:"am",visual:"child"},
{section:"Reading & Writing",type:"choice",prompt:"Choose the missing word: She ___ happy.",opts:["am","is","are"],answer:"is",visual:"girl"},
{section:"Reading & Writing",type:"choice",prompt:"Choose the missing word: They ___ my friends.",opts:["am","is","are"],answer:"are",visual:"friends"},
{section:"Reading & Writing",type:"choice",prompt:"Choose the missing word: This is ___ apple.",opts:["a","an","the"],answer:"an",visual:"apples"},
{section:"Reading & Writing",type:"choice",prompt:"Read: 'Sam has a red bike.' What colour is Sam's bike?",opts:["Red","Blue","Green"],answer:"Red",visual:"bike"},
{section:"Reading & Writing",type:"choice",prompt:"What animal is this?",opts:["A penguin","A bear","A tiger"],answer:"A penguin",visual:"bird"},
{section:"Reading & Writing",type:"choice",prompt:"Read: 'Mia has a small white cat.' What does Mia have?",opts:["A dog","A cat","A rabbit"],answer:"A cat",visual:"cat"},
{section:"Reading & Writing",type:"choice",prompt:"Which shape is a triangle?",opts:["Circle","Square","Triangle"],answer:"Triangle",visual:"star"},
{section:"Reading & Writing",type:"choice",prompt:"Which word completes the sentence? This is a ___.",opts:["book","books","booking"],answer:"book",visual:"book"},
{section:"Reading & Writing",type:"choice",prompt:"Which word completes the sentence? I like ___.",opts:["apples","apple","appling"],answer:"apples",visual:"apples"},
{section:"Reading & Writing",type:"choice",prompt:"Choose the correct sentence.",opts:["He are happy.","He is happy.","He am happy."],answer:"He is happy.",visual:"child"},
{section:"Reading & Writing",type:"choice",prompt:"Choose the correct sentence.",opts:["They is friends.","They am friends.","They are friends."],answer:"They are friends.",visual:"friends"},
{section:"Reading & Writing",type:"choice",prompt:"Read the mini-story: 'Leo has a blue bag. He puts a book in it.' What is in the bag?",opts:["A book","A ball","A pencil"],answer:"A book",visual:"bag"},
{section:"Reading & Writing",type:"choice",prompt:"Read the mini-story: 'Lily is in the garden. She sees a yellow flower.' What does Lily see?",opts:["A yellow flower","A red ball","A blue bird"],answer:"A yellow flower",visual:"garden"},
{section:"Reading & Writing",type:"choice",prompt:"Read: 'It is sunny. The children are in the park.' Where are the children?",opts:["At school","In the park","At home"],answer:"In the park",visual:"park"},
{section:"Reading & Writing",type:"choice",prompt:"What animal is this?",opts:["A rabbit","A cat","A dog"],answer:"A rabbit",visual:"rabbit"},
{section:"Reading & Writing",type:"choice",prompt:"Which word is a colour?",opts:["Happy","Purple","Jump"],answer:"Purple",visual:"colours"},
{section:"Reading & Writing",type:"choice",prompt:"Which word is an animal?",opts:["Apple","Tiger","Table"],answer:"Tiger",visual:"animal"},
{section:"Reading & Writing",type:"choice",prompt:"Which word is a number?",opts:["Seven","Yellow","Mother"],answer:"Seven",visual:"number"},
{section:"Reading & Writing",type:"choice",prompt:"Which word is a family member?",opts:["Brother","Ball","Blue"],answer:"Brother",visual:"family"},
{section:"Reading & Writing",type:"choice",prompt:"Which word is an object?",opts:["Pencil","Happy","Run"],answer:"Pencil",visual:"pencils"}];

const bands:[string,number,number][]=[
["Strong Pre-A1 Foundation",48,53],["Developing Pre-A1",40,47],["Early Pre-A1",30,39],["Beginning English",0,29]
];

function Illustration({kind}:{kind:string}){const animal=kind==="dog"||kind==="cat"||kind==="rabbit"||kind==="bird"||kind==="animal";const type=animal?kind:(kind==="girls"?"girls":kind==="friends"||kind==="family"||kind==="girl"||kind==="child"?"people":kind==="book"||kind==="desk"||kind==="pencils"||kind==="number"||kind==="colours"?"school":kind==="park"||kind==="garden"||kind==="bike"||kind==="kite"?"outdoor":kind==="ball"||kind==="apples"||kind==="table"||kind==="teddy"?"home":"object");return <svg className="scene-svg" viewBox="0 0 640 300" role="img" aria-label="Illustration"><defs><linearGradient id="sky" x1="0" x2="1"><stop offset="0" stopColor="#eef7ff"/><stop offset="1" stopColor="#faf3ff"/></linearGradient><linearGradient id="ground" x1="0" x2="1"><stop offset="0" stopColor="#dff2dc"/><stop offset="1" stopColor="#cdebd1"/></linearGradient></defs><rect width="640" height="300" rx="24" fill="url(#sky)"/><circle cx="545" cy="55" r="30" fill="#ffd76a" opacity=".75"/><path d="M0 205 Q160 170 320 205 T640 200 V300 H0Z" fill="url(#ground)"/><g className="scene-shadow"><ellipse cx="320" cy="247" rx="135" ry="20"/></g>{type==="animal"&&<Tiger/>}{type==="dog"&&<Dog/>}{type==="cat"&&<Cat/>}{type==="rabbit"&&<Rabbit/>}{type==="bird"&&<Bird/>}{type==="people"&&<People kind={kind}/>} {type==="girls"&&<Girls/>}{type==="school"&&<School kind={kind}/>} {type==="outdoor"&&<Outdoor kind={kind}/>} {type==="home"&&<Home kind={kind}/>} {type==="object"&&<ObjectScene kind={kind}/>}<circle cx="88" cy="58" r="7" fill="#fff" opacity=".8"/><circle cx="108" cy="46" r="11" fill="#fff" opacity=".7"/><circle cx="130" cy="60" r="6" fill="#fff" opacity=".8"/></svg>}
function Dog(){return <g><path d="M400 205 q-35-70 10-112 q55-35 105 15 q35 35 5 97Z" fill="#b9794f"/><path d="M415 108 q-35-45-2-58 l38 36Z" fill="#8d573d"/><path d="M505 105 q38-46 40-4 l-25 43Z" fill="#8d573d"/><ellipse cx="448" cy="142" rx="7" ry="9" fill="#29263a"/><ellipse cx="493" cy="142" rx="7" ry="9" fill="#29263a"/><ellipse cx="470" cy="161" rx="12" ry="9" fill="#6c4561"/><path d="M458 174 q12 12 24 0" fill="none" stroke="#6c4561" strokeWidth="4" strokeLinecap="round"/><path d="M445 113 q25 18 35 3" stroke="#fff" strokeWidth="28" strokeLinecap="round" opacity=".9"/><rect x="90" y="142" width="125" height="78" rx="4" fill="#efd49b" stroke="#b8744c" strokeWidth="7"/><path d="M78 145 L152 83 L226 145" fill="#e97855" stroke="#b95d43" strokeWidth="7"/><path d="M135 220 v-45 q0-18 18-18t18 18v45" fill="#80513e"/><ellipse cx="550" cy="229" rx="27" ry="10" fill="#4f8ce8"/><circle cx="575" cy="221" r="15" fill="#ffbd3c"/></g>}
function Cat(){return <g><rect x="150" y="95" width="330" height="22" rx="9" fill="#6fa7dc"/><path d="M190 117v92M440 117v92" stroke="#a96f43" strokeWidth="16"/><path d="M205 209h-30M455 209h30" stroke="#a96f43" strokeWidth="12"/><path d="M285 208 q-30-65 0-102 q42-36 85 0 q30 34 2 102Z" fill="#a9adb8"/><path d="M300 111 l18-25 18 30M352 116 l18-30 17 27" fill="#90949f"/><circle cx="316" cy="139" r="6" fill="#29263a"/><circle cx="355" cy="139" r="6" fill="#29263a"/><path d="M332 151 l8 6 8-6" fill="#6c4561"/><path d="M110 210 q15-70 42-70 q28 0 42 70" fill="#63b57b"/><rect x="120" y="210" width="64" height="18" rx="8" fill="#b97d55"/></g>}
function Rabbit(){return <g><ellipse cx="335" cy="170" rx="72" ry="62" fill="#f4f1ed"/><ellipse cx="305" cy="83" rx="22" ry="62" fill="#f4f1ed" stroke="#d7d1cc" strokeWidth="5"/><ellipse cx="365" cy="83" rx="22" ry="62" fill="#f4f1ed" stroke="#d7d1cc" strokeWidth="5"/><circle cx="314" cy="153" r="7"/><circle cx="356" cy="153" r="7"/><ellipse cx="335" cy="172" rx="9" ry="7" fill="#e89aa5"/><circle cx="470" cy="215" r="18" fill="#8bcf75"/><path d="M450 215 q20-55 45 0" fill="none" stroke="#63ad59" strokeWidth="12"/></g>}
function Bird(){return <g><ellipse cx="330" cy="145" rx="72" ry="52" fill="#6f8ff5"/><circle cx="390" cy="125" r="38" fill="#7ea0ff"/><path d="M410 125 l45 15 -45 15Z" fill="#ffbd3c"/><circle cx="400" cy="116" r="6"/><path d="M280 145 q-55 5-65 45 q50 5 80-15" fill="#5877df"/><path d="M150 90 v130" stroke="#9a694d" strokeWidth="16"/><circle cx="150" cy="80" r="55" fill="#63b57b"/></g>}
function Tiger(){return <g><ellipse cx="330" cy="165" rx="92" ry="72" fill="#f2a64b"/><circle cx="330" cy="105" r="62" fill="#f5ad4e"/><path d="M285 80 l20-28 20 35M375 80 l-20-28-20 35" fill="#e9963e"/><circle cx="310" cy="105" r="7"/><circle cx="350" cy="105" r="7"/><path d="M325 120 h10 l-5 8Z" fill="#6c4561"/><path d="M300 130 l20 8M360 130 l-20 8" stroke="#6c4561" strokeWidth="4"/><path d="M285 150 l20 10M375 150 l-20 10" stroke="#6c4561" strokeWidth="10"/></g>}
function People({kind}:{kind:string}){return <g>{[0,1,2].map((i)=><g key={i} transform={`translate(${180+i*120} 0)`}><circle cx="0" cy="105" r="30" fill={i===0?"#f0b47b":"#d99a6b"}/><path d="M-45 220 q0-75 45-82 q45 7 45 82Z" fill={i===0?"#ff6f9a":i===1?"#62a5e8":"#55b98c"}/><circle cx="-10" cy="102" r="4"/><circle cx="10" cy="102" r="4"/></g>)}{kind==="family"&&<text x="318" y="270" textAnchor="middle" fontSize="20" fontWeight="700" fill="#6d4aff">Family</text>}</g>}
function Girls(){return <g>{[0,1,2].map((i)=><g key={i} transform={`translate(${185+i*120} 0)`}><circle cx="0" cy="105" r="28" fill="#f0b47b"/><path d="M-43 220 q0-75 43-82 q43 7 43 82Z" fill={i===0?"#ff6f9a":i===1?"#62a5e8":"#55b98c"}/>{i===0&&<path d="M-38 84 q38-52 76 0 h-18 q-20-22-40 0Z" fill="#ffbd3c"/>}</g>)}</g>}
function School({kind}:{kind:string}){return <g><rect x="115" y="125" width="410" height="105" rx="14" fill="#fff" stroke="#d9d2ee" strokeWidth="6"/><rect x="150" y="145" width="150" height="65" rx="8" fill="#eef4ff"/><path d="M180 180h85M180 195h55" stroke="#8da4c7" strokeWidth="7" strokeLinecap="round"/><path d="M350 210V130" stroke="#b98a63" strokeWidth="18"/><path d="M330 145h120" stroke="#b98a63" strokeWidth="14"/><circle cx="400" cy="115" r="28" fill="#ffcf92"/><path d="M375 100 q25-30 50 0" fill="#6d4aff"/><rect x="470" y="178" width="28" height="45" rx="6" fill="#ffbd3c"/><text x="320" y="75" textAnchor="middle" fontSize="22" fontWeight="800" fill="#6d4aff">{kind==="number"?"3":kind==="colours"?"COLOUR":"ENGLISH"}</text></g>}
function Outdoor({kind}:{kind:string}){return <g><rect x="95" y="168" width="14" height="70" fill="#9a694d"/><circle cx="102" cy="135" r="58" fill="#63b57b"/><path d="M450 215 q0-90 65-90" fill="none" stroke="#b98a63" strokeWidth="12"/><path d="M505 120 l45 35 -50 10Z" fill="#ff6f9a"/><circle cx="390" cy="220" r="25" fill="#ffbd3c"/><text x="320" y="65" textAnchor="middle" fontSize="22" fontWeight="800" fill="#6d4aff">{kind==="bike"?"OUTDOOR FUN":kind==="kite"?"FLY A KITE":"PARK DAY"}</text></g>}
function Home({kind}:{kind:string}){return <g><rect x="125" y="92" width="390" height="140" rx="18" fill="#fff" stroke="#d9d2ee" strokeWidth="6"/><rect x="175" y="135" width="95" height="80" rx="12" fill="#cfe7ff"/><rect x="375" y="145" width="85" height="70" rx="12" fill="#efd49b"/><path d="M390 145 l28-35 28 35" fill="#e97855"/><circle cx="320" cy="165" r="42" fill={kind==="teddy"?"#b77a50":"#ffcf92"}/><text x="320" y="75" textAnchor="middle" fontSize="22" fontWeight="800" fill="#6d4aff">{kind==="teddy"?"TEDDY BEAR":"HOME"}</text></g>}
function ObjectScene({kind}:{kind:string}){return <g><rect x="150" y="155" width="340" height="65" rx="18" fill="#fff" stroke="#d9d2ee" strokeWidth="5"/><circle cx="230" cy="187" r="28" fill="#ff6f70"/><circle cx="320" cy="187" r="28" fill="#6d9cf7"/><circle cx="410" cy="187" r="28" fill="#ffbd3c"/><text x="320" y="90" textAnchor="middle" fontSize="22" fontWeight="800" fill="#6d4aff">{kind==="ball"?"COLOUR":kind==="apples"?"APPLES":"LOOK & CHOOSE"}</text></g>}
function Logo(){return <div className="logo"><div className="logo-mark">E</div><div><strong>English Explorer</strong><small>Young Learner Assessment</small></div></div>}

export default function Home(){
 const [i,setI]=useState(0),[answers,setAnswers]=useState<string[]>([]),[done,setDone]=useState(false),[name,setName]=useState(""),[started,setStarted]=useState(false);
 const q=questions[i];
 const objectiveCount=questions.filter(x=>x.answer!=="personal").length;
 useEffect(()=>{if(started&&q.section==="Listening"&&q.audio&&typeof window!=="undefined"){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.audio);u.lang="en-US";u.rate=.82;u.pitch=1;window.speechSynthesis.speak(u)}return()=>{if(typeof window!=="undefined")window.speechSynthesis.cancel()}},[i,q.audio,q.section,started]);
 const play=()=>{if(typeof window==="undefined"||!q.audio)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(q.audio);u.lang="en-US";u.rate=.82;window.speechSynthesis.speak(u)};
 const score=useMemo(()=>answers.reduce((s,a,n)=>s+(a&&questions[n].answer&&questions[n].answer!=="personal"&&a.trim().toLowerCase()===questions[n].answer!.toLowerCase()?1:0),0),[answers]);
 const choose=(a:string)=>{const x=[...answers];x[i]=a;setAnswers(x)};
 const next=()=>i<questions.length-1?setI(i+1):setDone(true);
 const sectionStart=i===0||questions[i-1]?.section!==q.section;
 if(!started)return <main className="shell"><nav><Logo/><span className="trust">Designed for young learners</span></nav><section className="hero"><div className="hero-copy"><div className="eyebrow">PRE-A1 · AGE 7–8</div><h1>English skills,<br/><em>made an adventure.</em></h1><p>A friendly online assessment that checks listening, reading and writing through short, familiar tasks.</p><div className="hero-actions"><button className="primary" onClick={()=>setStarted(true)}>Start assessment <span>→</span></button><span className="meta">About 25–30 minutes · 55 questions</span></div></div><div className="hero-art"><div className="orbit o1"/><div className="orbit o2"/><div className="explorer-card"><div className="fox-face">E</div><div className="spark s1">✦</div><div className="spark s2">✦</div><div className="mini-card"><b>LISTEN</b><span>🔊</span></div><div className="mini-card m2"><b>READ</b><span>ABC</span></div><div className="mini-card m3"><b>WRITE</b><span>✎</span></div></div></div></section><section className="feature-row"><div><b>01</b><span>Listening</span><small>Short audio + picture choices</small></div><div><b>02</b><span>Reading & Writing</span><small>Pictures, words & mini-stories</small></div><div><b>03</b><span>Progress report</span><small>Clear results for families</small></div></section><footer>English Explorer · Pre-A1 Progress Assessment · Not an official Cambridge or CEFR certificate</footer></main>;
 if(done){const band=bands.find(b=>score>=b[1]&&score<=b[2])?.[0]||"Beginning English";return <main className="shell"><nav><Logo/></nav><section className="result-page"><div className="result-top"><div className="result-badge">ASSESSMENT COMPLETE</div><h1>Well done{name?", "+name:""}!</h1><p>Your English Explorer journey is complete.</p></div><div className="result-grid"><div className="score-card"><span>Objective score</span><strong>{score}<i> / {objectiveCount}</i></strong><b>{band}</b><div className="score-line"><span style={{width:(score/objectiveCount*100)+"%"}}/></div></div><div className="profile-card"><h3>Skills checked</h3><div><span>Listening</span><b>{answers.filter((a,k)=>questions[k].section==="Listening"&&a&&questions[k].answer===a).length} / 20</b></div><div><span>Reading & Writing</span><b>{answers.filter((a,k)=>questions[k].section==="Reading & Writing"&&a&&questions[k].answer&&questions[k].answer!=="personal"&&a.toLowerCase()===questions[k].answer!.toLowerCase()).length} / 33</b></div><p>Use this report as a learning snapshot. It is not an official CEFR qualification.</p></div></div><div className="certificate"><div className="cert-mark">E</div><small>ENGLISH EXPLORER</small><h2>Pre-A1 Progress Certificate</h2><p>This certifies that</p><strong>{name||"the learner"}</strong><p>completed the English Explorer assessment.</p><div className="cert-foot"><span>Young Learner · Pre-A1</span><span>Progress Certificate</span></div></div><div className="result-actions"><button className="primary" onClick={()=>window.print()}>Print / Save PDF</button><button className="ghost" onClick={()=>{setAnswers([]);setI(0);setDone(false);setStarted(true)}}>Try again</button></div></section></main>}
 return <main className="shell"><nav><Logo/><div className="progress-wrap"><span>{i+1} / {questions.length}</span><div><i style={{width:((i+1)/questions.length*100)+"%"}}/></div></div></nav>{sectionStart&&<div className="section-intro"><span>{q.section==="Listening"?"01":"02"}</span><div><b>{q.section}</b><small>{q.section==="Listening"?"Listen carefully. You can play the audio again.":"Read the text and look at the picture before you answer."}</small></div></div>}<section className="test-card"><div className="task-label">{q.type==="tf"?"PICTURE + SENTENCE":q.type==="input"?"WORD WORK":q.section==="Listening"?"LISTEN & CHOOSE":"READ & CHOOSE"}</div><div className="visual-panel"><Illustration kind={q.visual}/></div><div className="question-copy"><h1>{q.prompt}</h1>{q.section==="Listening"&&<button className="audio-btn" onClick={play}>▶ <span>Play audio again</span></button>}</div>{i===0&&<div className="namebox"><label>Learner first name <span>(optional)</span></label><input value={name} onChange={e=>setName(e.target.value)} placeholder="First name"/></div>}{q.type==="input"?<input className="answer-input" value={answers[i]||""} onChange={e=>choose(e.target.value)} placeholder="Type your answer" autoComplete="off"/>:<div className="options">{q.opts!.map((o,n)=><button key={o} className={answers[i]===o?"selected":""} onClick={()=>choose(o)}><span className="option-letter">{String.fromCharCode(65+n)}</span>{o}</button>)}</div>}<button className="next-btn" disabled={!answers[i]?.trim()} onClick={next}>{i===questions.length-1?"Finish assessment":"Continue"}<span>→</span></button></section><div className="test-note">Take your time. There are no trick questions.</div></main>
}